### ISSUE TITLE
Change color of Timeline Items

### ISSUE THREAD

**Issue by Alby407** [ivan-lednev/obsidian-day-planner#122]
Is there a way to change the colors of timeline items? I'm mostly working with a light theme, in which it is difficult to read the items in the timeline, as the text is colored black and the timeline items are dark-colored.

**Comment by MitchAllain** [comment]
You can redefine the event block colors and text colors in a [CSS snippet](https://help.obsidian.md/How+to/Add+custom+styles#Use+Themes+and+or+CSS+snippets).

The file `obsidian-day-planner/examples/timeline-example.css` in this repo shows some examples of redefining the event block colors.

Using the web inspector (Ctrl + Shift + i) I was able to find the text styles and include a CSS rule to turn them black

```css
.header_title.svelte-e43ld1.svelte-e43ld1, .ei_Copy.svelte-e43ld1.svelte-e43ld1, .ei_Title.svelte-e43ld1.svelte-e43ld1, .ce_title.svelte-e43ld1.svelte-e43ld1 {
     color: #000 !important;
}
```

I do think it would be nice to add an optional light color scheme to the timeline view for this project, so that users without CSS experience can quickly select a theme that matches their vault settings.

Until then, here is my entire CSS snippet for the timeline view, including a white to green gradient for the event blocks.

```css
.event_item:hover{
    background-color: var(--interactive-accent-hover) !important;
}

.event_item_color1 {
  background-color: #FFFFFFff !important;
}

.event_item_color2 {
  background-color: #F3F8F1ff !important;
}

.event_item_color3 {
  background-color: #E7F0E3ff !important;
}

.event_item_color4 {
  background-color: #DBE9D6ff !important;
}

.event_item_color5 {
  background-color: #CFE1C8ff !important;
}

.event_item_color6 {
  background-color: #C2DABAff !important;
}

.event_item_color7 {
  background-color: #B6D2ACff !important;
}

.event_item_color8 {
  background-color: #AACB9Fff !important;
}

.event_item_color9 {
  background-color: #9EC391ff !important;
}

.event_item_color10 {
  background-color: #92BC83ff !important;
}

.header_title.svelte-e43ld1.svelte-e43ld1, .ei_Copy.svelte-e43ld1.svelte-e43ld1, .ei_Title.svelte-e43ld1.svelte-e43ld1, .ce_title.svelte-e43ld1.svelte-e43ld1 {
     color: #000 !important;
}
```

This works well with my minimal theme.

![image](https://user-images.githubusercontent.com/8354131/140657617-65249b27-7d4c-48b2-bb5f-951a11641331.png)
